import * as core from '@actions/core';
import * as github from '@actions/github';
import { A11yIssue } from '../state/types';

type Octokit = ReturnType<typeof github.getOctokit>;

const CHECK_NAME = 'Accessibility Review';
const MAX_ANNOTATIONS = 50;

interface Annotation {
  path: string;
  start_line: number;
  end_line: number;
  annotation_level: 'failure' | 'warning' | 'notice';
  message: string;
  title?: string;
  raw_details?: string;
}

export async function createAccessibilityCheckRun(
  octokit: Octokit,
  owner: string,
  repo: string,
  headSha: string,
  violations: A11yIssue[],
  goodPractices: A11yIssue[]
): Promise<{ checkRunId: number; annotationCount: number }> {
  core.info(`Creating Check Run for ${headSha}`);

  const { data: checkRun } = await octokit.rest.checks.create({
    owner,
    repo,
    name: CHECK_NAME,
    head_sha: headSha,
    status: 'in_progress',
    started_at: new Date().toISOString(),
  });

  const checkRunId = checkRun.id;
  core.info(`Created Check Run #${checkRunId}`);

  const allIssues = [...violations, ...goodPractices];
  const annotations = buildAnnotations(allIssues);
  const annotationCount = Math.min(annotations.length, MAX_ANNOTATIONS);

  const totalIssues = allIssues.length;
  const truncated = totalIssues > MAX_ANNOTATIONS;

  const conclusion = violations.length > 0 ? 'failure' : 'success';
  const summary = formatCheckSummary(violations, goodPractices, truncated);

  core.info(`Updating Check Run with ${annotationCount} annotations (conclusion: ${conclusion})`);

  await octokit.rest.checks.update({
    owner,
    repo,
    check_run_id: checkRunId,
    status: 'completed',
    completed_at: new Date().toISOString(),
    conclusion,
    output: {
      title: CHECK_NAME,
      summary,
      annotations: annotations.slice(0, MAX_ANNOTATIONS),
    },
  });

  if (truncated) {
    core.info(`Note: ${totalIssues - MAX_ANNOTATIONS} issues not shown due to GitHub annotation limit`);
  }

  return { checkRunId, annotationCount };
}

function buildAnnotations(issues: A11yIssue[]): Annotation[] {
  const annotations: Annotation[] = [];

  for (const issue of issues) {
    if (!issue || !issue.file) continue;

    const line = issue.line && issue.line > 0 ? issue.line : 1;

    const annotationLevel = issue.severity === 'VIOLATION' ? 'failure' : 'notice';

    const title = issue.wcag_criterion
      ? `WCAG ${issue.wcag_criterion} (Level ${issue.wcag_level || 'A'})`
      : 'Accessibility Issue';

    const message = issue.title || 'Accessibility issue found';

    let rawDetails = '';
    if (issue.description) {
      rawDetails += issue.description;
    }
    if (issue.suggestion) {
      if (rawDetails) rawDetails += '\n\n';
      rawDetails += `Suggested fix: ${issue.suggestion}`;
    }

    annotations.push({
      path: issue.file,
      start_line: line,
      end_line: line,
      annotation_level: annotationLevel,
      message,
      title,
      raw_details: rawDetails || undefined,
    });
  }

  return annotations;
}

function formatCheckSummary(
  violations: A11yIssue[],
  goodPractices: A11yIssue[],
  truncated: boolean
): string {
  const sections: string[] = [];

  const violationCount = violations.length;
  const goodPracticeCount = goodPractices.length;
  const total = violationCount + goodPracticeCount;

  if (total === 0) {
    sections.push('✅ **No issues found.**');
    sections.push('');
    sections.push('The code appears to follow WCAG 2.2 guidelines.');
    return sections.join('\n');
  }

  const parts: string[] = [];
  if (violationCount > 0) {
    parts.push(`🔴 **${violationCount} violation${violationCount !== 1 ? 's' : ''}**`);
  }
  if (goodPracticeCount > 0) {
    parts.push(`🟢 **${goodPracticeCount} good practice${goodPracticeCount !== 1 ? 's' : ''}**`);
  }

  sections.push(`**Found:** ${parts.join(' · ')}`);
  sections.push('');

  if (truncated) {
    sections.push(`⚠️ Showing ${MAX_ANNOTATIONS} of ${total} issues (GitHub annotation limit)`);
    sections.push('');
  }

  if (violationCount > 0) {
    sections.push('---');
    sections.push('');
    sections.push('### ⚠️ Violations (must fix)');
    sections.push('');
    sections.push('These issues **must be fixed** to meet WCAG 2.2 requirements.');
    sections.push('');
    sections.push('See annotations above for details.');
  }

  if (goodPracticeCount > 0) {
    sections.push('---');
    sections.push('');
    sections.push('### 🟢 Good Practices (recommended)');
    sections.push('');
    sections.push('These improvements are **recommended** to enhance accessibility.');
    sections.push('');
    sections.push('See annotations above for details.');
  }

  sections.push('');
  sections.push('---');
  sections.push('*🤖 Generated by WCAG 2.2 Accessibility Review*');

  return sections.join('\n');
}

export function formatCheckNoIssuesSummary(): string {
  return [
    '## ✅ Accessibility Review',
    '',
    '**No issues found.**',
    '',
    'The code appears to follow WCAG 2.2 guidelines.',
    '',
    '---',
    '*🤖 Generated by WCAG 2.2 Accessibility Review*',
  ].join('\n');
}