"""PR comment management for aggregated feedback."""

from typing import Dict, List, Optional

from .client import GitHubClient
from ..prompts.severity import Severity, get_emoji


# Unique identifier for bot comments
COMMENT_IDENTIFIER = "<!-- a11y-pr-review-bot -->"


class CommentManager:
    """Manage aggregated PR comments for accessibility issues."""

    def __init__(self, github_client: GitHubClient):
        """
        Initialize the comment manager.

        Args:
            github_client: GitHub API client
        """
        self.github_client = github_client

    def post_or_update_comment(
        self,
        pr_number: int,
        issues: List[Dict],
        summary: Optional[str] = None
    ) -> Dict:
        """
        Post or update an aggregated comment for SUGGESTION and NIT issues.

        Args:
            pr_number: Pull request number
            issues: List of accessibility issues (will filter to SUGGESTION/NIT)
            summary: Optional summary text from LLM

        Returns:
            API response
        """
        # Filter to SUGGESTION and NIT only
        low_priority_issues = [
            issue for issue in issues
            if issue.get('severity') in ('SUGGESTION', 'NIT')
        ]

        if not low_priority_issues:
            return {}

        # Check for existing comment
        existing = self.github_client.find_bot_comment(
            pr_number,
            COMMENT_IDENTIFIER
        )

        # Build comment body
        body = self._build_comment_body(low_priority_issues, summary)

        if existing:
            # Update existing comment
            return self.github_client.update_comment(
                comment_id=existing['id'],
                body=body
            )
        else:
            # Create new comment
            return self.github_client.create_comment(
                pr_number=pr_number,
                body=body
            )

    def _build_comment_body(
        self,
        issues: List[Dict],
        summary: Optional[str] = None
    ) -> str:
        """
        Build the comment body for aggregated issues.

        Args:
            issues: List of SUGGESTION/NIT issues
            summary: Optional summary text

        Returns:
            Formatted comment body
        """
        lines = [
            COMMENT_IDENTIFIER,
            "## ♿ Accessibility Suggestions",
            ""
        ]

        if summary:
            lines.extend([
                f"> {summary}",
                ""
            ])

        # Group issues by file
        issues_by_file = {}
        for issue in issues:
            file_path = issue.get('file', 'unknown')
            if file_path not in issues_by_file:
                issues_by_file[file_path] = []
            issues_by_file[file_path].append(issue)

        # Build sections per file
        for file_path, file_issues in issues_by_file.items():
            lines.extend([
                f"### 📄 `{file_path}`",
                ""
            ])

            for issue in file_issues:
                severity = issue.get('severity', 'SUGGESTION')
                emoji = get_emoji(Severity[severity])
                wcag = issue.get('wcag_criterion', '')

                lines.append(f"**{emoji} Line {issue.get('line', '?')}: {issue.get('title', 'Issue')}**")
                lines.append(f"- WCAG {wcag} (Level {issue.get('wcag_level', 'AA')})")
                lines.append(f"- {issue.get('description', 'No description')}")
                lines.append("")

        # Add footer
        lines.extend([
            "---",
            "",
            "<details>",
            "<summary>📋 WCAG Reference</summary>",
            "",
            "- **SUGGESTION**: Recommended improvements for better accessibility",
            "- **NIT**: Minor improvements and best practices",
            "",
            "These issues don't block users but improve the overall accessibility experience.",
            "</details>",
            "",
            "*🤖 This comment was automatically generated by the a11y-pr-review action.*"
        ])

        return '\n'.join(lines)

    def create_summary_comment(
        self,
        pr_number: int,
        total_issues: int,
        critical_count: int,
        important_count: int,
        suggestion_count: int,
        nit_count: int,
        llm_summary: Optional[str] = None
    ) -> Dict:
        """
        Create a summary comment for the PR.

        Args:
            pr_number: Pull request number
            total_issues: Total issues found
            critical_count: Number of critical issues
            important_count: Number of important issues
            suggestion_count: Number of suggestions
            nit_count: Number of nits
            llm_summary: LLM-generated summary

        Returns:
            API response
        """
        if total_issues == 0:
            body = self._build_no_issues_body()
        else:
            body = self._build_summary_body(
                total_issues,
                critical_count,
                important_count,
                suggestion_count,
                nit_count,
                llm_summary
            )

        # Check for existing comment
        existing = self.github_client.find_bot_comment(
            pr_number,
            COMMENT_IDENTIFIER
        )

        if existing:
            return self.github_client.update_comment(
                comment_id=existing['id'],
                body=body
            )
        else:
            return self.github_client.create_comment(
                pr_number=pr_number,
                body=body
            )

    def _build_no_issues_body(self) -> str:
        """Build comment body when no issues found."""
        return '\n'.join([
            COMMENT_IDENTIFIER,
            "## ✅ Accessibility Review",
            "",
            "Great job! No accessibility issues were found in this pull request.",
            "",
            "Your changes appear to follow WCAG 2.1/2.2 guidelines.",
            "",
            "---",
            "*🤖 This comment was automatically generated by the a11y-pr-review action.*"
        ])

    def _build_summary_body(
        self,
        total: int,
        critical: int,
        important: int,
        suggestion: int,
        nit: int,
        llm_summary: Optional[str]
    ) -> str:
        """Build comment body with summary."""
        lines = [
            COMMENT_IDENTIFIER,
            "## ♿ Accessibility Review Summary",
            ""
        ]

        if llm_summary:
            lines.extend([
                f"> {llm_summary}",
                ""
            ])

        lines.append("### 📊 Issue Counts")
        lines.append("")
        lines.append(f"| Severity | Count |")
        lines.append("|----------|-------|")
        lines.append(f"| 🔴 Critical | {critical} |")
        lines.append(f"| 🟠 Important | {important} |")
        lines.append(f"| 🟡 Suggestion | {suggestion} |")
        lines.append(f"| ⚪ Nit | {nit} |")
        lines.append(f"| **Total** | **{total}** |")
        lines.append("")

        if critical > 0 or important > 0:
            lines.extend([
                "> ⚠️ Critical and Important issues have been posted as inline review comments.",
                ""
            ])

        lines.extend([
            "---",
            "*🤖 This comment was automatically generated by the a11y-pr-review action.*"
        ])

        return '\n'.join(lines)