import * as github from '@actions/github';
import { A11yIssue, MAX_ISSUES } from '../state/types';

type Octokit = ReturnType<typeof github.getOctokit>;

const COMMENT_IDENTIFIER = '<!-- a11y-review -->';

export async function createOrUpdateComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  body: string
): Promise<number> {
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100,
  });

  const botComment = comments.find(c =>
    c.user?.type === 'Bot' &&
    c.body?.includes(COMMENT_IDENTIFIER)
  );

  const fullBody = `${COMMENT_IDENTIFIER}\n${body}`;

  if (botComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: botComment.id,
      body: fullBody,
    });
    return botComment.id;
  } else {
    const { data: newComment } = await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: fullBody,
    });
    return newComment.id;
  }
}

export function formatIssueComment(issues: A11yIssue[]): string {
  const limitedIssues = issues.slice(0, MAX_ISSUES);

  const critical = limitedIssues.filter(i => i?.severity === 'CRITICAL');
  const important = limitedIssues.filter(i => i?.severity === 'IMPORTANT');
  const suggestions = limitedIssues.filter(i => i?.severity === 'SUGGESTION');
  const nits = limitedIssues.filter(i => i?.severity === 'NIT');

  const sections: string[] = ['## ♿ Accessibility Review', ''];

  // Summary line
  const total = limitedIssues.length;
  const parts: string[] = [];
  if (critical.length > 0) parts.push(`🔴 ${critical.length} critical`);
  if (important.length > 0) parts.push(`🟡 ${important.length} important`);
  if (suggestions.length > 0) parts.push(`🟢 ${suggestions.length} suggestion${suggestions.length !== 1 ? 's' : ''}`);
  if (nits.length > 0) parts.push(`⚪ ${nits.length} nit${nits.length !== 1 ? 's' : ''}`);

  sections.push(`**Found ${total} issue${total !== 1 ? 's' : ''}:** ${parts.join(', ')}`);
  sections.push('');

  // CRITICAL issues (fallback for when not inline)
  if (critical.length > 0) {
    sections.push('### 🔴 Critical Issues');
    sections.push('');
    for (const issue of critical) {
      sections.push(formatIssueItem(issue));
    }
  }

  // IMPORTANT issues (fallback for when not inline)
  if (important.length > 0) {
    sections.push('### 🟡 Important Issues');
    sections.push('');
    for (const issue of important) {
      sections.push(formatIssueItem(issue));
    }
  }

  // SUGGESTIONS
  if (suggestions.length > 0) {
    sections.push('### 🟢 Suggestions');
    sections.push('');
    for (const issue of suggestions) {
      sections.push(formatIssueItem(issue));
    }
  }

  // NITS
  if (nits.length > 0) {
    sections.push('### ⚪ Minor Issues');
    sections.push('');
    for (const issue of nits) {
      sections.push(formatIssueItem(issue));
    }
  }

  sections.push('---');
  sections.push('*🤖 Generated by accessibility review*');

  return sections.join('\n');
}

function formatIssueItem(issue: A11yIssue): string {
  const lines: string[] = [];
  const location = (issue.file || 'Unknown') + (issue.line ? `:${issue.line}` : '');
  
  lines.push(`- **${location}** - ${issue.title || issue.description || 'No description'}`);
  if (issue.wcag_criterion) {
    lines.push(`  - WCAG ${issue.wcag_criterion} (Level ${issue.wcag_level || 'A'})`);
  }
  if (issue.suggestion) {
    lines.push(`  - **Fix:** ${issue.suggestion}`);
  }
  lines.push('');
  
  return lines.join('\n');
}

export function formatNoIssuesComment(summary?: string): string {
  const lines: string[] = [
    '## ✅ Accessibility Review',
    '',
  ];

  if (summary) {
    lines.push(`> ${summary}`, '');
  }

  lines.push('No accessibility issues were found.');
  lines.push('');
  lines.push('The changes appear to follow WCAG 2.1/2.2 guidelines.');
  lines.push('');
  lines.push('---');
  lines.push('*🤖 Generated by accessibility review*');

  return lines.join('\n');
}

export function formatDraftSkipComment(): string {
  return [
    '## ♿ Accessibility Review',
    '',
    '⏸️ **Skipped** - This PR is a draft.',
    '',
    'Accessibility analysis will run when the PR is marked as ready for review.',
    '',
    '---',
    '*🤖 Generated by accessibility review*',
  ].join('\n');
}