import * as github from '@actions/github';
import { A11yIssue, MAX_ISSUES } from '../state/types';

type Octokit = ReturnType<typeof github.getOctokit>;

const COMMENT_IDENTIFIER = '<!-- a11y-review -->';

export async function createOrUpdateComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  prNumber: number,
  body: string
): Promise<number> {
  const { data: comments } = await octokit.rest.issues.listComments({
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100,
  });

  const botComment = comments.find(c =>
    c.user?.type === 'Bot' &&
    c.body?.includes(COMMENT_IDENTIFIER)
  );

  const fullBody = `${COMMENT_IDENTIFIER}\n${body}`;

  if (botComment) {
    await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: botComment.id,
      body: fullBody,
    });
    return botComment.id;
  } else {
    const { data: newComment } = await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: fullBody,
    });
    return newComment.id;
  }
}

export function formatIssueComment(issues: A11yIssue[]): string {
  const limitedIssues = issues.slice(0, MAX_ISSUES);

  const violations = limitedIssues.filter(i => i?.severity === 'VIOLATION');
  const goodPractices = limitedIssues.filter(i => i?.severity === 'GOOD_PRACTICE');

  const sections: string[] = ['## ♿ Accessibility Review', ''];

  // Summary line
  if (violations.length === 0 && goodPractices.length === 0) {
    sections.push('✅ **No issues found.**');
    sections.push('');
    sections.push('The code appears to follow WCAG 2.2 guidelines.');
  } else {
    const parts: string[] = [];
    if (violations.length > 0) parts.push(`🔴 **${violations.length} violation${violations.length !== 1 ? 's' : ''}**`);
    if (goodPractices.length > 0) parts.push(`🟢 **${goodPractices.length} good practice${goodPractices.length !== 1 ? 's' : ''}**`);
    
    sections.push(`**Found:** ${parts.join(' · ')}`);
    sections.push('');

    if (violations.length > 0) {
      sections.push('---');
      sections.push('');
      sections.push('### ⚠️ Violations');
      sections.push('');
      sections.push('These issues **must be fixed** to meet WCAG 2.2 requirements.');
      sections.push('');

      for (const issue of violations) {
        sections.push(formatIssueItem(issue));
      }
    }

    if (goodPractices.length > 0) {
      sections.push('---');
      sections.push('');
      sections.push('### 🟢 Good Practices');
      sections.push('');
      sections.push('These are **recommended improvements** that enhance accessibility but are not required.');
      sections.push('');

      for (const issue of goodPractices) {
        sections.push(formatIssueItem(issue));
      }
    }
  }

  sections.push('---');
  sections.push('*🤖 Generated by WCAG 2.2 Accessibility Review*');

  return sections.join('\n');
}

function formatIssueItem(issue: A11yIssue): string {
  const lines: string[] = [];
  const location = (issue.file || 'Unknown') + (issue.line ? `:${issue.line}` : '');
  
  lines.push(`**${location}**`);
  lines.push(`> ${issue.title || 'Accessibility issue'}`);
  if (issue.wcag_criterion) {
    lines.push(`> WCAG ${issue.wcag_criterion} (Level ${issue.wcag_level || 'A'})`);
  }
  if (issue.description) {
    lines.push(`> ${issue.description}`);
  }
  if (issue.suggestion) {
    lines.push('>');
    lines.push(`> \`\`\`${issue.suggestion}\`\`\``);
  }
  lines.push('');
  
  return lines.join('\n');
}

export function formatNoIssuesComment(summary?: string): string {
  const lines: string[] = [
    '## ✅ Accessibility Review',
    '',
  ];

  if (summary) {
    lines.push(`> ${summary}`, '');
  }

  lines.push('**No issues found.**');
  lines.push('');
  lines.push('The code appears to follow WCAG 2.2 guidelines.');
  lines.push('');
  lines.push('---');
  lines.push('*🤖 Generated by WCAG 2.2 Accessibility Review*');

  return lines.join('\n');
}

export function formatDraftSkipComment(): string {
  return [
    '## ♿ Accessibility Review',
    '',
    '⏸️ **Skipped** - This PR is a draft.',
    '',
    'Accessibility analysis will run when the PR is marked as ready for review.',
    '',
    '---',
    '*🤖 Generated by WCAG 2.2 Accessibility Review*',
  ].join('\n');
}