/**
 * PR comment management for aggregated feedback
 */

import { GitHubClient } from './client';
import { A11yIssue } from '../types';
import { Severity, getSeverityEmoji } from '../prompts/severity';

const COMMENT_IDENTIFIER = '<!-- a11y-pr-review-bot -->';

export class CommentManager {
  private github: GitHubClient;

  constructor(github: GitHubClient) {
    this.github = github;
  }

  async postOrUpdateComment(
    prNumber: number,
    issues: A11yIssue[],
    summary?: string
  ): Promise<void> {
    // Filter to SUGGESTION and NIT only
    const lowPriorityIssues = issues.filter(
      i => i.severity === Severity.SUGGESTION || i.severity === Severity.NIT
    );

    if (lowPriorityIssues.length === 0) {
      return;
    }

    // Build comment body
    const body = this.buildCommentBody(lowPriorityIssues, summary);

    // Check for existing comment
    const existing = await this.github.findBotComment(prNumber, COMMENT_IDENTIFIER);

    if (existing) {
      await this.github.updateComment(existing.id, body);
    } else {
      await this.github.createComment(prNumber, body);
    }
  }

  private buildCommentBody(issues: A11yIssue[], summary?: string): string {
    const lines = [COMMENT_IDENTIFIER, '## ♿ Accessibility Suggestions', ''];

    if (summary) {
      lines.push(`> ${summary}`, '');
    }

    // Group issues by file
    const issuesByFile: Record<string, A11yIssue[]> = {};
    for (const issue of issues) {
      if (!issuesByFile[issue.file]) {
        issuesByFile[issue.file] = [];
      }
      issuesByFile[issue.file].push(issue);
    }

    // Build sections per file
    for (const [filePath, fileIssues] of Object.entries(issuesByFile)) {
      lines.push(`### 📄 \`${filePath}\``, '');

      for (const issue of fileIssues) {
        const emoji = getSeverityEmoji(issue.severity as Severity);
        lines.push(`**${emoji} Line ${issue.line}: ${issue.title}**`);
        lines.push(`- WCAG ${issue.wcag_criterion} (Level ${issue.wcag_level})`);
        lines.push(`- ${issue.description}`, '');
      }
    }

    // Add footer
    lines.push(
      '---',
      '',
      '<details>',
      '<summary>📋 WCAG Reference</summary>',
      '',
      '- **SUGGESTION**: Recommended improvements for better accessibility',
      '- **NIT**: Minor improvements and best practices',
      '',
      "These issues don't block users but improve the overall accessibility experience.",
      '</details>',
      '',
      '*🤖 This comment was automatically generated by the a11y-pr-review action.*'
    );

    return lines.join('\n');
  }

  async createSummaryComment(
    prNumber: number,
    totalIssues: number,
    criticalCount: number,
    importantCount: number,
    suggestionCount: number,
    nitCount: number,
    llmSummary?: string
  ): Promise<void> {
    let body: string;

    if (totalIssues === 0) {
      body = [
        COMMENT_IDENTIFIER,
        '## ✅ Accessibility Review',
        '',
        'Great job! No accessibility issues were found in this pull request.',
        '',
        'Your changes appear to follow WCAG 2.1/2.2 guidelines.',
        '',
        '---',
        '*🤖 This comment was automatically generated by the a11y-pr-review action.*',
      ].join('\n');
    } else {
      const lines = [COMMENT_IDENTIFIER, '## ♿ Accessibility Review Summary', ''];

      if (llmSummary) {
        lines.push(`> ${llmSummary}`, '');
      }

      lines.push('### 📊 Issue Counts', '');
      lines.push('| Severity | Count |');
      lines.push('|----------|-------|');
      lines.push(`| 🔴 Critical | ${criticalCount} |`);
      lines.push(`| 🟠 Important | ${importantCount} |`);
      lines.push(`| 🟡 Suggestion | ${suggestionCount} |`);
      lines.push(`| ⚪ Nit | ${nitCount} |`);
      lines.push(`| **Total** | **${totalIssues}** |`);
      lines.push('');

      if (criticalCount > 0 || importantCount > 0) {
        lines.push('> ⚠️ Critical and Important issues have been posted as inline review comments.', '');
      }

      lines.push('---');
      lines.push('*🤖 This comment was automatically generated by the a11y-pr-review action.*');

      body = lines.join('\n');
    }

    // Check for existing comment
    const existing = await this.github.findBotComment(prNumber, COMMENT_IDENTIFIER);

    if (existing) {
      await this.github.updateComment(existing.id, body);
    } else {
      await this.github.createComment(prNumber, body);
    }
  }
}